name: Build and Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create GH Pages
      run: |
        git remote set-url origin https://RodrigoDLPontes:${{ secrets.GITHUB_TOKEN }}@github.com/luciankt/visualization-tool.git
        git config --global user.email "lucianktash@gmail.com"
        git config --global user.name "luciankt"
        npm ci
        npm run deploy
